// Cloudflare Worker — fetches YouTube captions and returns WebVTT
// Deploy with: npx wrangler deploy worker.js --name audiofilter-captions

export default {
  async fetch(request) {
    // CORS headers
    const corsHeaders = {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    };

    if (request.method === 'OPTIONS') {
      return new Response(null, { headers: corsHeaders });
    }

    const url = new URL(request.url);
    const videoId = url.searchParams.get('v');
    const lang = url.searchParams.get('lang') || 'en';

    if (!videoId || !/^[\w-]{11}$/.test(videoId)) {
      return new Response(JSON.stringify({ error: 'Missing or invalid video ID. Use ?v=VIDEO_ID' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    try {
      const result = await getYouTubeCaptions(videoId, lang);
      return new Response(JSON.stringify(result), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    } catch (err) {
      return new Response(JSON.stringify({ error: err.message }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
  },
};

async function getYouTubeCaptions(videoId, lang) {
  // Step 1: Fetch the YouTube watch page
  const pageResponse = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      'Accept-Language': 'en-US,en;q=0.9',
    },
  });

  if (!pageResponse.ok) {
    throw new Error(`YouTube returned ${pageResponse.status}`);
  }

  const html = await pageResponse.text();

  // Step 2: Extract ytInitialPlayerResponse JSON
  const startMarker = 'var ytInitialPlayerResponse = ';
  let startIndex = html.indexOf(startMarker);

  if (startIndex === -1) {
    // Try alternate pattern (sometimes it's set differently)
    const altMarker = 'ytInitialPlayerResponse = ';
    startIndex = html.indexOf(altMarker);
    if (startIndex === -1) {
      throw new Error('Could not find player response in page');
    }
    startIndex += altMarker.length;
  } else {
    startIndex += startMarker.length;
  }

  // Find the JSON object by counting braces
  let depth = 0;
  let end = startIndex;
  for (; end < html.length; end++) {
    if (html[end] === '{') depth++;
    else if (html[end] === '}') {
      depth--;
      if (depth === 0) { end++; break; }
    }
  }

  let playerResponse;
  try {
    playerResponse = JSON.parse(html.substring(startIndex, end));
  } catch (e) {
    throw new Error('Failed to parse player response JSON');
  }

  // Step 3: Extract caption tracks
  const captionTracks =
    playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

  if (!captionTracks || captionTracks.length === 0) {
    throw new Error('No captions available for this video');
  }

  // Step 4: Find best matching language track
  // Prefer manual captions over auto-generated (kind !== 'asr')
  let track = captionTracks.find(t => t.languageCode === lang && t.kind !== 'asr');
  if (!track) track = captionTracks.find(t => t.languageCode === lang);
  if (!track) track = captionTracks.find(t => t.languageCode.startsWith(lang.split('-')[0]));
  if (!track) track = captionTracks[0]; // fallback

  // Step 5: Fetch caption data in json3 format
  const captionUrl = track.baseUrl + '&fmt=json3';
  const captionResponse = await fetch(captionUrl, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
    },
  });

  if (!captionResponse.ok) {
    throw new Error(`Caption fetch failed: ${captionResponse.status}`);
  }

  const captionData = await captionResponse.json();

  // Step 6: Convert to WebVTT
  const webvtt = convertToWebVTT(captionData);

  return {
    webvtt,
    language: track.languageCode,
    languageName: track.name?.simpleText || track.languageCode,
    isAutoGenerated: track.kind === 'asr',
    availableLanguages: captionTracks.map(t => ({
      code: t.languageCode,
      name: t.name?.simpleText || t.languageCode,
      isAutoGenerated: t.kind === 'asr',
    })),
  };
}

function convertToWebVTT(captionData) {
  const events = captionData?.events || [];
  let vtt = 'WEBVTT\n\n';
  let cueIndex = 1;

  for (const event of events) {
    // Skip events without text segments (timing markers)
    if (!event.segs) continue;

    const text = event.segs
      .map(seg => seg.utf8 || '')
      .join('')
      .trim()
      .replace(/\n{2,}/g, '\n');

    if (!text) continue;

    const startMs = event.tStartMs || 0;
    const durationMs = event.dDurationMs || 0;
    const endMs = startMs + durationMs;

    vtt += `${cueIndex}\n`;
    vtt += `${msToVttTime(startMs)} --> ${msToVttTime(endMs)}\n`;
    vtt += `${text}\n\n`;
    cueIndex++;
  }

  return vtt;
}

function msToVttTime(ms) {
  const hours = Math.floor(ms / 3600000);
  const minutes = Math.floor((ms % 3600000) / 60000);
  const seconds = Math.floor((ms % 60000) / 1000);
  const millis = ms % 1000;

  return (
    String(hours).padStart(2, '0') + ':' +
    String(minutes).padStart(2, '0') + ':' +
    String(seconds).padStart(2, '0') + '.' +
    String(millis).padStart(3, '0')
  );
}
